import { ToolMetadata, ToolId } from "@/lib/ffmpeg/types";

export const TOOLS: ToolMetadata[] = [
  // 1. Smart Video Compressor
  {
    id: "video-compressor",
    slug: "video-compressor",
    name: "Smart Video Compressor",
    shortName: "Compress Video",
    tagline: "Reduce video file size up to 90% without noticeable quality loss",
    description:
      "Compress MP4, MOV, MKV and WebM videos directly in your browser with fine-grained CRF controls and instant resolution downscaling. 100% private with no server uploads.",
    category: "Optimization",
    iconName: "Minimize2",
    badge: "Most Popular",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".flv"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Ultra-Fast (Wasm SIMD)",
    seoTitle: "Free Private Video Compressor Online | No Upload Limit (Wasm)",
    seoDescription:
      "Compress large video files directly inside your browser. No file size limits, zero server uploads, 100% private WebAssembly compression with CRF & resolution controls.",
    seoKeywords: [
      "video compressor",
      "compress mp4 online",
      "reduce video size free",
      "private video compressor",
      "client-side video compression",
      "wasm ffmpeg compressor",
    ],
    features: [
      {
        title: "Intelligent Bitrate Ceiling",
        description: "Strictly enforces target file sizes so videos never balloon during compression.",
        icon: "Sliders",
      },
      {
        title: "Instant Resolution Scaling",
        description: "Downscale to 1080p, 720p, or 480p with bicubic filtering for massive file savings.",
        icon: "Maximize",
      },
      {
        title: "Zero Server Uploads",
        description: "Your recordings never leave your device. All transcoding happens in RAM via WebAssembly.",
        icon: "ShieldCheck",
      },
    ],
    steps: [
      { step: 1, title: "Select Video", description: "Pick any video file from your computer or phone." },
      { step: 2, title: "Choose Target Reduction", description: "Pick 50% Smaller, 70% Smaller, or set exact target MB." },
      { step: 3, title: "Compress & Download", description: "Click 'Start Compress' and download your optimized video." },
    ],
    faqs: [
      {
        question: "Is my video uploaded to any server?",
        answer: "No! All processing runs 100% locally in your web browser memory using WebAssembly.",
      },
      {
        question: "How does target size compression work?",
        answer: "We dynamically compute the exact bitrate ceiling from your video length so the output never exceeds your desired file size.",
      },
    ],
  },

  // 2. Video to GIF Converter
  {
    id: "video-to-gif",
    slug: "video-to-gif",
    name: "Video to GIF Converter",
    shortName: "Make GIF",
    tagline: "Turn video clips into ultra-smooth, high-definition animated GIFs",
    description:
      "Convert MP4, MOV, or WebM clips into animated GIFs using two-pass palette generation for vibrant colors and crisp details.",
    category: "Conversion",
    iconName: "Film",
    badge: "High Quality",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".webm", ".mkv", ".avi"],
    outputExtension: "gif",
    outputMimeType: "image/gif",
    estimatedSpeed: "Fast (Two-Pass Palette)",
    seoTitle: "Video to GIF Converter Online - High Quality HD GIFs",
    seoDescription: "Convert video clips to crisp, high-quality animated GIFs with custom FPS and two-pass color palette generation.",
    seoKeywords: ["video to gif", "convert mp4 to gif", "hd gif maker", "online gif converter"],
    features: [
      { title: "Two-Pass Color Palette", description: "Generates custom 256-color palette without color banding.", icon: "Palette" },
      { title: "Custom Frame Rate", description: "Select 10, 15, 24, or 30 FPS for silky smooth motion.", icon: "Gauge" },
      { title: "In-Browser Preview", description: "Preview animated GIF immediately before downloading.", icon: "PlayCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Video Clip", description: "Choose a short video clip (under 30s recommended)." },
      { step: 2, title: "Set FPS & Width", description: "Select your desired frame rate and width." },
      { step: 3, title: "Generate GIF", description: "Click convert and save your crisp animated GIF." },
    ],
    faqs: [
      { question: "Why are the GIFs so clear?", answer: "We compute an individualized color palette for each frame using Lanczos scaling." },
    ],
  },

  // 3. Audio Extractor
  {
    id: "audio-extractor",
    slug: "audio-extractor",
    name: "Audio Extractor & Converter",
    shortName: "Extract Audio",
    tagline: "Extract pristine audio from any video into MP3, WAV, or AAC",
    description: "Rip soundtrack, speech, and sound effects from any video format into high-bitrate MP3, lossless WAV, or AAC audio files.",
    category: "Audio",
    iconName: "Music",
    badge: "Studio Audio",
    acceptedTypes: ["video/*", "audio/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".flv", ".mp3", ".wav", ".aac"],
    outputExtension: "mp3",
    outputMimeType: "audio/mpeg",
    estimatedSpeed: "Instant",
    seoTitle: "Extract Audio from Video Online Free - MP3, WAV, AAC Converter",
    seoDescription: "Extract audio tracks from MP4, MKV, MOV videos into 320kbps MP3, AAC or lossless WAV files.",
    seoKeywords: ["extract audio from video", "mp4 to mp3 converter", "video to wav", "rip audio from video"],
    features: [
      { title: "Multiple Formats", description: "Export as universal MP3, Apple AAC, or studio lossless WAV.", icon: "FileAudio" },
      { title: "High Bitrate (320kbps)", description: "Crystal-clear high fidelity encoding presets.", icon: "Radio" },
      { title: "Lightning Fast", description: "Demux and extract audio in seconds.", icon: "Zap" },
    ],
    steps: [
      { step: 1, title: "Select Video", description: "Upload any video or audio file." },
      { step: 2, title: "Choose Format", description: "Pick MP3, WAV, or AAC and select bitrate." },
      { step: 3, title: "Extract & Download", description: "Download your clean audio file." },
    ],
    faqs: [{ question: "Is WAV format lossless?", answer: "Yes, WAV exports 16-bit uncompressed PCM studio master audio." }],
  },

  // 4. Video Trimmer & Splitter
  {
    id: "video-trimmer",
    slug: "video-trimmer",
    name: "Video Trimmer & Splitter",
    shortName: "Trim Video",
    tagline: "Cut and trim videos with millisecond timeline precision",
    description: "Cut unwanted sections, trim video start and end times with live synchronized preview and ultra-fast lossless stream-copy.",
    category: "Video",
    iconName: "Scissors",
    badge: "Dual Timeline",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Instant (Lossless Copy)",
    seoTitle: "Free Video Trimmer Online - Cut & Split Video Clips Fast",
    seoDescription: "Trim and cut video clips with dual-handle timeline slider, real-time video scrub, and fast stream-copy cut.",
    seoKeywords: ["video trimmer", "cut video online", "split video", "trim mp4 online"],
    features: [
      { title: "Dual Timeline Handles", description: "Interactive start and end handles for exact cuts.", icon: "SlidersHorizontal" },
      { title: "Live Video Scrub", description: "Player follows handle movement frame by frame.", icon: "Eye" },
      { title: "Lossless Stream-Copy", description: "Instant export without re-encoding video.", icon: "Cpu" },
    ],
    steps: [
      { step: 1, title: "Load Video", description: "Upload the video you want to cut." },
      { step: 2, title: "Set Handles", description: "Drag start/end handles to mark keep segment." },
      { step: 3, title: "Trim Video", description: "Export the trimmed segment instantly." },
    ],
    faqs: [{ question: "How fast is stream-copy?", answer: "Stream-copy completes in under a second because it copies raw video packets." }],
  },

  // 5. Video Speed Controller
  {
    id: "speed-controller",
    slug: "speed-controller",
    name: "Video Speed Controller",
    shortName: "Change Speed",
    tagline: "Speed up or create cinematic slow-motion videos with pitch correction",
    description: "Adjust playback speed from 0.25x slow-motion up to 4.0x fast-forward with automated audio pitch preservation.",
    category: "Video",
    iconName: "FastForward",
    badge: "0.25x - 4x",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Video Speed Controller Online - Fast Forward & Slow Motion Video",
    seoDescription: "Speed up or slow down videos from 0.25x to 4x with audio pitch correction and smooth frame presentation.",
    seoKeywords: ["video speed controller", "speed up video online", "slow motion video maker"],
    features: [
      { title: "0.25x to 4x Multipliers", description: "One-click preset speed buttons.", icon: "Zap" },
      { title: "Audio Pitch Correction", description: "Maintains natural vocal pitch with FFmpeg atempo.", icon: "Volume2" },
      { title: "Smooth PTS Presentation", description: "Recalculates video timestamps for stutter-free playback.", icon: "Activity" },
    ],
    steps: [
      { step: 1, title: "Select Video", description: "Upload the clip you want to speed or slow." },
      { step: 2, title: "Select Multiplier", description: "Pick 0.5x, 2x, 4x, etc." },
      { step: 3, title: "Render & Save", description: "Download your speed-adjusted video." },
    ],
    faqs: [{ question: "Does pitch stay normal?", answer: "Yes, voices sound normal without chipmunk effect." }],
  },

  // 6. Video Mute
  {
    id: "video-mute",
    slug: "video-mute",
    name: "Video Mute & Audio Stripper",
    shortName: "Mute Video",
    tagline: "Remove audio tracks from any video in milliseconds",
    description: "Strip background noise, unwanted audio, or confidential speech from your videos in 1-click with zero quality loss.",
    category: "Audio",
    iconName: "VolumeX",
    badge: "1-Click",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".flv"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Instant (100ms)",
    seoTitle: "Remove Audio from Video Online Free - 1-Click Video Muter",
    seoDescription: "Mute and strip audio from MP4, MOV, WebM videos instantly without re-encoding video.",
    seoKeywords: ["mute video online", "remove audio from video", "strip audio from mp4"],
    features: [
      { title: "Zero Re-encoding", description: "Copies video stream 1:1 with pure zero loss.", icon: "Shield" },
      { title: "Sub-Second Processing", description: "Mutes even 1GB files in milliseconds.", icon: "Clock" },
      { title: "Smaller File Size", description: "Removes unnecessary audio stream channels.", icon: "ArrowDownCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select any video containing audio." },
      { step: 2, title: "Click Mute", description: "Click 1-Click Mute to strip audio." },
      { step: 3, title: "Download Silent Video", description: "Save your clean video immediately." },
    ],
    faqs: [{ question: "Does video quality change?", answer: "Not a single pixel changes; video is stream-copied bit for bit." }],
  },

  // 7. Universal Format Converter
  {
    id: "format-converter",
    slug: "format-converter",
    name: "Universal Video Format Converter",
    shortName: "Convert Format",
    tagline: "Transcode seamlessly between MP4, WebM, MKV, MOV, AVI, and FLV",
    description: "Convert video containers and codecs across all major formats for maximum device compatibility and web streaming.",
    category: "Conversion",
    iconName: "RefreshCw",
    badge: "All Formats",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".flv", ".wmv", ".m4v"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Universal Video Converter Online - Convert MP4, WebM, MKV, MOV, AVI",
    seoDescription: "Convert videos between MP4, WebM, MKV, MOV, AVI, and FLV right inside your web browser.",
    seoKeywords: ["video format converter", "convert mov to mp4", "convert mkv to mp4", "webm to mp4 converter"],
    features: [
      { title: "6+ Major Formats", description: "Support for MP4, WebM, MKV, MOV, AVI, and FLV.", icon: "FileCode" },
      { title: "Web Streaming Optimized", description: "Applies faststart flags for progressive web playback.", icon: "Globe" },
      { title: "High Fidelity", description: "Crisp H.264 / VP8 transcode with custom presets.", icon: "Sparkles" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select any video file." },
      { step: 2, title: "Select Target Format", description: "Pick MP4, WebM, MKV, or MOV." },
      { step: 3, title: "Convert & Save", description: "Download your newly formatted video." },
    ],
    faqs: [{ question: "Which format is best for social media?", answer: "MP4 with H.264 and AAC is 100% universal across all platforms." }],
  },

  // 8. Social Aspect Ratio Resizer
  {
    id: "aspect-ratio-resizer",
    slug: "aspect-ratio-resizer",
    name: "Social Aspect Ratio Resizer",
    shortName: "Resize for Social",
    tagline: "Format videos for TikTok, Reels, Shorts (9:16), Instagram (1:1), and YouTube (16:9)",
    description: "Fit videos perfectly to 9:16 vertical, 1:1 square, or 16:9 widescreen formats using smart center cropping or letterbox padding.",
    category: "Optimization",
    iconName: "Smartphone",
    badge: "TikTok & Reels",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Social Media Video Resizer - Fit for TikTok, Reels, YouTube Shorts",
    seoDescription: "Resize landscape videos to 9:16 vertical for TikTok and Instagram Reels with crop or letterbox padding.",
    seoKeywords: ["video aspect ratio resizer", "resize video for tiktok", "convert horizontal to vertical video"],
    features: [
      { title: "Social Presets", description: "9:16 Reels/Shorts, 1:1 Instagram, 16:9 YouTube.", icon: "LayoutGrid" },
      { title: "Crop vs Pad", description: "Choose full screen center-crop or elegant letterbox padding.", icon: "Maximize2" },
      { title: "Crisp 1080p Dimensions", description: "Standard high definition exports.", icon: "CheckCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select your landscape or square video." },
      { step: 2, title: "Pick Aspect Ratio", description: "Choose 9:16, 1:1, 16:9 and Crop/Pad mode." },
      { step: 3, title: "Export & Post", description: "Download ready-to-publish social video." },
    ],
    faqs: [{ question: "What is letterbox padding?", answer: "Padding keeps the full video in view and fills empty borders with clean black margins." }],
  },

  // 9. Video Watermark & Logo Adder
  {
    id: "video-watermark",
    slug: "video-watermark",
    name: "Video Watermark & Logo Adder",
    shortName: "Add Watermark",
    tagline: "Add custom text watermark or transparent PNG logo branding to your videos",
    description: "Protect and brand your video clips with customizable text watermarks or image logos with 5 position presets and opacity control.",
    category: "Video",
    iconName: "Image",
    badge: "Branding",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Add Watermark & Logo to Video Online Free (No Server Upload)",
    seoDescription: "Add text watermarks or PNG logos to videos in browser. Custom opacity, position controls, 100% private.",
    seoKeywords: ["add watermark to video", "video logo adder", "watermark video online free", "brand video watermark"],
    features: [
      { title: "Text & Image Watermarks", description: "Type custom text or upload transparent PNG logo.", icon: "Image" },
      { title: "5 Position Presets", description: "Place in Top-Left, Top-Right, Bottom-Left, Bottom-Right, or Center.", icon: "LayoutGrid" },
      { title: "Opacity & Size Slider", description: "Subtle translucent branding with scale controls.", icon: "Sliders" },
    ],
    steps: [
      { step: 1, title: "Select Video", description: "Upload the video you want to brand." },
      { step: 2, title: "Configure Watermark", description: "Type text or select position & opacity." },
      { step: 3, title: "Apply & Download", description: "Export your newly branded video." },
    ],
    faqs: [{ question: "Can I use transparent PNG logos?", answer: "Yes, alpha transparency is fully preserved." }],
  },

  // 10. Video Rotate & Flip
  {
    id: "video-rotate",
    slug: "video-rotate",
    name: "Video Rotate & Flip",
    shortName: "Rotate Video",
    tagline: "Rotate sideways videos by 90°, 180°, 270° or flip horizontally/vertically",
    description: "Fix sideways smartphone recordings and mirror videos horizontally or vertically with 1-click rotation presets.",
    category: "Video",
    iconName: "RotateCw",
    badge: "Orientation",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Rotate Video Online - 90, 180, 270 Degree & Flip Mirror",
    seoDescription: "Rotate smartphone videos 90, 180, 270 degrees clockwise or flip horizontal/vertical mirror free in browser.",
    seoKeywords: ["rotate video online", "fix sideways video", "rotate mp4 90 degrees", "flip video horizontally"],
    features: [
      { title: "90°, 180°, 270° Rotation", description: "Fix any landscape or portrait phone angle.", icon: "RotateCw" },
      { title: "Horizontal & Vertical Flip", description: "Mirror video selfie recordings easily.", icon: "RefreshCw" },
      { title: "Maintains Full Quality", description: "Crisp re-encode with proper metadata orientation.", icon: "CheckCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select your sideways or inverted video." },
      { step: 2, title: "Choose Rotation Angle", description: "Click 90° Clockwise, 180°, 270° or Flip." },
      { step: 3, title: "Save Video", description: "Download your upright video." },
    ],
    faqs: [{ question: "Why are some phone videos sideways?", answer: "Some cameras save incorrect rotation metadata; this tool hardcodes the orientation." }],
  },

  // 11. Video Reverse / Rewind Maker
  {
    id: "video-reverse",
    slug: "video-reverse",
    name: "Video Reverse & Rewind Maker",
    shortName: "Reverse Video",
    tagline: "Play videos and audio backwards for magic rewind effects",
    description: "Create mind-bending reverse videos for TikTok and YouTube Shorts with reverse video frames and synchronized reverse audio.",
    category: "Video",
    iconName: "Rewind",
    badge: "Rewind FX",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Reverse Video Online - Play Video Backwards (Rewind Maker)",
    seoDescription: "Reverse video clips and audio online for free. Create rewind effects for TikTok and Reels in browser.",
    seoKeywords: ["reverse video online", "play video backwards", "video rewind maker", "reverse mp4 video"],
    features: [
      { title: "Reverse Video Frames", description: "Renders motion from end to beginning seamlessly.", icon: "Rewind" },
      { title: "Reverse Audio FX", description: "Reverses soundtrack or mutes audio.", icon: "Volume2" },
      { title: "Perfect for Reels", description: "Create viral magic tricks and rewind videos.", icon: "Sparkles" },
    ],
    steps: [
      { step: 1, title: "Upload Clip", description: "Select a video clip (short clips recommended)." },
      { step: 2, title: "Choose Audio Option", description: "Select reverse audio or silent mute." },
      { step: 3, title: "Generate Rewind", description: "Download your reversed video clip." },
    ],
    faqs: [{ question: "Is this suitable for long videos?", answer: "For memory efficiency in browser, clips under 45 seconds work fastest." }],
  },

  // 12. Video Frame Extractor
  {
    id: "frame-extractor",
    slug: "frame-extractor",
    name: "Video Frame Extractor & Screenshot Grabber",
    shortName: "Grab Frame",
    tagline: "Capture high-resolution PNG or JPG screenshots from exact video timestamps",
    description: "Extract pristine, uncompressed full-resolution still photo frames and thumbnails from any video clip at exact millisecond marks.",
    category: "Conversion",
    iconName: "Eye",
    badge: "HD Snapshot",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi"],
    outputExtension: "png",
    outputMimeType: "image/png",
    estimatedSpeed: "Instant",
    seoTitle: "Extract Frame from Video Online - High Res Video Screenshot Grabber",
    seoDescription: "Capture exact HD & 4K frames from video clips as PNG or JPG images with live timeline scrubber.",
    seoKeywords: ["extract frame from video", "video screenshot grabber", "video to photo converter", "capture frame from mp4"],
    features: [
      { title: "Millisecond Precision", description: "Scrub to the exact frame you want to extract.", icon: "SlidersHorizontal" },
      { title: "Lossless PNG Export", description: "Saves maximum native video resolution without compression artifacts.", icon: "Image" },
      { title: "Instant Snapshot", description: "Demuxes frame in under 200 milliseconds.", icon: "Zap" },
    ],
    steps: [
      { step: 1, title: "Select Video", description: "Upload your video file." },
      { step: 2, title: "Scrub to Frame", description: "Use timeline slider to find the perfect shot." },
      { step: 3, title: "Save Photo", description: "Download high-res PNG or JPG image." },
    ],
    faqs: [{ question: "Is the snapshot full resolution?", answer: "Yes! If the video is 1080p or 4K, the image is exported at the full native pixel dimensions." }],
  },

  // 13. Video Filters & Color Grading
  {
    id: "video-filters",
    slug: "video-filters",
    name: "Video Filters & Color Grading",
    shortName: "Color Filters",
    tagline: "Apply cinematic color grading, vintage filters, and brightness adjustments",
    description: "Enhance your footage with aesthetic presets (Cyberpunk, Vintage Sepia, B&W, Warm Sunset) or adjust brightness, contrast, and saturation.",
    category: "Video",
    iconName: "Sun",
    badge: "Cinematic",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Video Color Filters & Grading Online - Free Video Effects",
    seoDescription: "Apply vintage, cyberpunk, black and white filters or adjust brightness, contrast, and saturation in browser.",
    seoKeywords: ["video color grading online", "video filters free", "adjust video brightness", "black and white video filter"],
    features: [
      { title: "Cinematic Color Presets", description: "Cyberpunk, Sepia, Vintage Film, B&W, Warm Sunset.", icon: "Palette" },
      { title: "Fine Slider Controls", description: "Fine-tune Brightness, Contrast, Saturation, and Gamma.", icon: "Sliders" },
      { title: "Instant Playback", description: "Download studio-color graded video.", icon: "PlayCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select the video you want to enhance." },
      { step: 2, title: "Choose Filter or Sliders", description: "Pick a preset or adjust color sliders." },
      { step: 3, title: "Render & Download", description: "Export your enhanced video." },
    ],
    faqs: [{ question: "Can I adjust dark videos?", answer: "Yes, increasing Brightness and Gamma will brighten underexposed dark video clips." }],
  },

  // 14. GIF to MP4 Video Converter
  {
    id: "gif-to-video",
    slug: "gif-to-video",
    name: "GIF to MP4 Video Converter",
    shortName: "GIF to MP4",
    tagline: "Convert heavy animated GIFs into 95% smaller looping MP4 videos",
    description: "Transform bulky, slow-loading GIFs into super-lightweight, high-performance MP4 videos that load instantly on all websites.",
    category: "Conversion",
    iconName: "Film",
    badge: "95% Smaller",
    acceptedTypes: ["image/gif"],
    acceptedExtensions: [".gif"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "GIF to MP4 Converter Online Free - Reduce GIF Size by 95%",
    seoDescription: "Convert heavy GIF animations into lightweight looping MP4 videos with WebAssembly in browser.",
    seoKeywords: ["gif to mp4", "convert gif to video", "reduce gif file size", "gif to mp4 converter online"],
    features: [
      { title: "95% File Size Reduction", description: "Turns a 30MB GIF into an ultra-lean 1.5MB MP4.", icon: "Minimize2" },
      { title: "Seamless Web Playback", description: "HTML5 video plays smoothly with hardware GPU acceleration.", icon: "Zap" },
      { title: "YUV420p Compatibility", description: "Ensures playback across every browser and mobile device.", icon: "CheckCircle" },
    ],
    steps: [
      { step: 1, title: "Upload GIF", description: "Select any animated GIF file." },
      { step: 2, title: "Configure Quality", description: "Select standard or high-fidelity CRF." },
      { step: 3, title: "Download MP4", description: "Save your ultra-lightweight looping video." },
    ],
    faqs: [{ question: "Why is MP4 so much smaller than GIF?", answer: "GIF is a 1987 uncompressed frame format, whereas MP4 uses modern inter-frame H.264 compression." }],
  },

  // 15. Volume Booster & Normalizer
  {
    id: "volume-booster",
    slug: "volume-booster",
    name: "Volume Booster & Audio Normalizer",
    shortName: "Boost Volume",
    tagline: "Boost low video audio up to 300% or apply broadcast audio normalization",
    description: "Amplify quiet voices and sound in videos up to 3x, or apply standard EBU R128 audio normalization to fix uneven volume levels.",
    category: "Audio",
    iconName: "Volume2",
    badge: "Up to 300%",
    acceptedTypes: ["video/*", "audio/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".mp3", ".wav"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Instant",
    seoTitle: "Video Volume Booster Online - Amplify Quiet Audio & Normalize Sound",
    seoDescription: "Increase video and audio volume up to 300% or apply broadcast normalization for free in browser.",
    seoKeywords: ["video volume booster", "increase video volume", "audio normalizer online", "boost mp4 volume"],
    features: [
      { title: "Up to 300% Amplification", description: "Boost quiet microphone recordings with clean gain.", icon: "Volume2" },
      { title: "EBU R128 Normalizer", description: "Broadcast standard loudnorm leveling prevents ear-piercing jumps.", icon: "Radio" },
      { title: "Zero Video Re-encoding", description: "Transcodes audio track with video stream-copy for maximum speed.", icon: "Zap" },
    ],
    steps: [
      { step: 1, title: "Upload Video / Audio", description: "Select file with quiet or uneven audio." },
      { step: 2, title: "Set Volume Boost", description: "Choose 150%, 200%, 300% or Normalize." },
      { step: 3, title: "Download Loud Media", description: "Save your amplified video file." },
    ],
    faqs: [{ question: "What is Audio Normalization?", answer: "Normalization automatically boosts quiet parts and reins in loud peaks so everything sounds balanced." }],
  },

  // 16. Audio Noise Reduction / De-Noiser
  {
    id: "audio-denoiser",
    slug: "audio-denoiser",
    name: "Audio Noise Reduction & De-Noiser",
    shortName: "De-Noise Audio",
    tagline: "Remove microphone hiss, fan background noise, and room hum",
    description: "Clean up your video soundtrack and voice recordings with advanced FFT spectral noise suppression directly in your browser.",
    category: "Audio",
    iconName: "Mic",
    badge: "Clean Audio",
    acceptedTypes: ["video/*", "audio/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".mp3", ".wav"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Remove Background Noise from Video Online Free - Audio De-Noiser",
    seoDescription: "Remove mic hiss, AC fan noise, and background hum from video and audio tracks with WebAssembly.",
    seoKeywords: ["remove background noise from video", "audio denoiser online", "clean mic hiss", "noise reduction video"],
    features: [
      { title: "FFT Spectral Filter", description: "Suppresses steady state noise (fans, air conditioning, electrical hum).", icon: "Mic" },
      { title: "Noise Floor Adjustment", description: "Customizable sensitivity for light or aggressive noise reduction.", icon: "Sliders" },
      { title: "Crystal-Clear Speech", description: "Enhances vocal clarity for podcasts and webinars.", icon: "CheckCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Recording", description: "Select video or audio with background noise." },
      { step: 2, title: "Adjust Noise Sensitivity", description: "Choose light, medium, or deep suppression." },
      { step: 3, title: "Download Clean Audio", description: "Save your crystal-clear recording." },
    ],
    faqs: [{ question: "What types of noise does it remove?", answer: "It excels at continuous background noise like computer fans, AC hums, and microphone hiss." }],
  },

  // 17. Metadata & EXIF Stripper
  {
    id: "metadata-stripper",
    slug: "metadata-stripper",
    name: "Metadata & EXIF Privacy Shield",
    shortName: "Strip Metadata",
    tagline: "Wipe GPS location, camera serials, author info, and timestamps in 1-click",
    description: "Ensure complete privacy before sharing videos online by scrubbing GPS coordinates, phone serials, software tags, and timestamps.",
    category: "Privacy & Pro",
    iconName: "Lock",
    badge: "Privacy Shield",
    acceptedTypes: ["video/*", "audio/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Instant (50ms)",
    seoTitle: "Remove Video Metadata & EXIF Online Free - Privacy Shield",
    seoDescription: "Strip GPS location tags, camera model info, and creator metadata from video files in 1-click.",
    seoKeywords: ["remove video metadata", "strip exif from video", "remove gps from mp4", "clean video metadata"],
    features: [
      { title: "Scrub GPS & Device Info", description: "Wipes camera model, creation time, and geolocation tags.", icon: "Lock" },
      { title: "Instant Stream Copy", description: "Cleans metadata in milliseconds without touching video quality.", icon: "Zap" },
      { title: "100% Anonymous Sharing", description: "Safely share videos on social media without privacy leaks.", icon: "ShieldCheck" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select any video file." },
      { step: 2, title: "Click Strip Metadata", description: "Click 1-Click Scrub to clean all metadata." },
      { step: 3, title: "Download Anonymous File", description: "Save your privacy-protected video." },
    ],
    faqs: [{ question: "Does this affect video quality?", answer: "Zero quality loss. The video and audio streams are copied 1:1, only header tags are removed." }],
  },

  // 18. FFmpeg Developer Terminal
  {
    id: "ffmpeg-terminal",
    slug: "ffmpeg-terminal",
    name: "FFmpeg Developer Terminal",
    shortName: "Wasm Terminal",
    tagline: "Run custom FFmpeg commands directly in your browser with live log stream",
    description: "A sandbox for engineers, editors, and creators to execute raw FFmpeg command arguments with custom filters, presets, and real-time logs.",
    category: "Privacy & Pro",
    iconName: "Terminal",
    badge: "Dev Mode",
    acceptedTypes: ["video/*", "audio/*", "image/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".gif", ".mp3", ".wav"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Variable",
    seoTitle: "Online FFmpeg Command Runner - Browser-Based WebAssembly Terminal",
    seoDescription: "Execute custom FFmpeg CLI commands in your browser with WebAssembly. Sandbox with recipes and live log terminal.",
    seoKeywords: ["ffmpeg online", "run ffmpeg in browser", "ffmpeg wasm terminal", "ffmpeg command runner"],
    features: [
      { title: "Raw Command Line", description: "Type any valid FFmpeg flags (-vf, -af, -c:v, -crf, etc.).", icon: "Terminal" },
      { title: "Pre-Built Recipes", description: "One-click load templates for 60fps, desaturate, high bitrate, etc.", icon: "FileCode" },
      { title: "Live Real-Time Logs", description: "Full standard error stream output from FFmpeg core.", icon: "Activity" },
    ],
    steps: [
      { step: 1, title: "Upload Input File", description: "Pick any media file." },
      { step: 2, title: "Enter FFmpeg Flags", description: "Type custom args or pick a template recipe." },
      { step: 3, title: "Execute & Download", description: "Run Wasm engine and download output." },
    ],
    faqs: [{ question: "Can I use complex filtergraphs?", answer: "Yes, -vf, -af, and -filter_complex are fully supported by the Wasm engine." }],
  },
];

export function getToolBySlug(slug: string): ToolMetadata | undefined {
  return TOOLS.find((tool) => tool.slug === slug || tool.id === slug);
}
