import { ToolMetadata, ToolId } from "@/lib/ffmpeg/types";

export const TOOLS: ToolMetadata[] = [
  // 1. Smart Video Compressor
  {
    id: "video-compressor",
    slug: "video-compressor",
    name: "Smart Video Compressor",
    shortName: "Compress Video",
    tagline: "Reduce video file size up to 90% without losing quality online for free",
    description:
      "Reduce video size and compress MP4, MOV, MKV, and WebM videos directly in your browser. Free video compressor for Discord (8MB & 10MB presets), iPhone, and PC with CRF bitrate ceilings and zero server uploads.",
    category: "Optimization",
    iconName: "Minimize2",
    badge: "Most Popular",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".flv"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Ultra-Fast (Wasm SIMD)",
    seoTitle: "Free Video Compressor Online - Reduce Video Size Without Losing Quality",
    seoDescription:
      "Reduce video file size online for free with our powerful video compressor. Best free online video compressor for Discord (8MB/10MB), iPhone, Android, and PC. Fast, private WebAssembly MP4 compressor alternative to Handbrake and Veed.",
    seoKeywords: [
      "reduce video size",
      "reduce video file size",
      "how to reduce video file size",
      "reduce video size online free",
      "how to reduce video size",
      "reduce video size online",
      "reduce video quality",
      "does dropbox reduce video quality",
      "reduce video file size without losing quality",
      "how to reduce video size on iphone",
      "how to reduce video quality",
      "how to reduce video file size without losing quality",
      "how to reduce video size without losing quality",
      "how to reduce video resolution",
      "how to reduce video file size on iphone",
      "how to reduce video file size on my phone",
      "how do i reduce video file size",
      "reduce video size free",
      "reduce video size iphone",
      "how to reduce video storage size",
      "video compressor",
      "video compressor for discord",
      "discord video compressor",
      "video compressor free",
      "free video compressor",
      "online video compressor",
      "video compressor online",
      "8mb video compressor",
      "handbrake video compressor",
      "freeconvert video compressor",
      "10mb video compressor",
      "video compressor online free",
      "free online video compressor",
      "video compressor app",
      "mp4 video compressor",
      "free video compressor online",
      "online video compressor free",
      "veed video compressor",
      "best video compressor",
      "video compressor discord",
    ],
    features: [
      {
        title: "Reduce Video File Size Without Quality Loss",
        description: "Psycho-visual CRF rate control preserves human-visible sharpness while reducing file size up to 90%.",
        icon: "Sliders",
      },
      {
        title: "Discord 8MB & 10MB Compression Presets",
        description: "One-click compression under Discord 8MB, 10MB, and 25MB limits with faststart web streaming playback.",
        icon: "Maximize",
      },
      {
        title: "Zero Server Uploads (100% Private)",
        description: "Your recordings never leave your device. All transcoding happens in local RAM via WebAssembly.",
        icon: "ShieldCheck",
      },
      {
        title: "Works on iPhone, Android & PC",
        description: "Reduce video storage size on iPhone camera roll or desktop browser without downloading third-party software.",
        icon: "Smartphone",
      },
    ],
    steps: [
      { step: 1, title: "Select Video File", description: "Pick any MP4, MOV, or WebM video from your phone or PC." },
      { step: 2, title: "Choose Target Reduction", description: "Select 50% Smaller, 70% Smaller, 8MB Discord preset, or set custom target MB." },
      { step: 3, title: "Compress & Download", description: "Click 'Start Compress' and download your optimized lightweight video." },
    ],
    faqs: [
      {
        question: "How to reduce video file size without losing quality?",
        answer:
          "To reduce video file size without losing quality, VideoReduce.com uses Constant Rate Factor (CRF 23-28) encoding and dynamic bitrate calculation. This compresses redundant background pixels while preserving crisp sharpness on focal points like faces and text.",
      },
      {
        question: "How to reduce video size on iPhone or Android phone?",
        answer:
          "Open Safari or Chrome on your iPhone or Android phone, navigate to VideoReduce.com, and select your video from your gallery. Choose a target compression preset (such as 70% reduction or 1080p downscaling) and hit compress. It processes right in your mobile browser without installing any app.",
      },
      {
        question: "How do I compress a video for Discord (8MB & 25MB)?",
        answer:
          "Select the Discord preset or set the Custom Target Size to 8MB (or 24MB for nitro/standard limits). The video compressor enforces an exact bitrate ceiling so the output file attaches smoothly in Discord chat.",
      },
      {
        question: "Does Dropbox or cloud storage reduce video quality?",
        answer:
          "Dropbox does not alter your original downloaded file, but its web video player streams a heavily compressed, low-quality preview. To share videos directly without losing quality or buffering, pre-compress them with VideoReduce.com before sending.",
      },
      {
        question: "How does VideoReduce compare to HandBrake, Veed, or FreeConvert?",
        answer:
          "Unlike HandBrake, VideoReduce requires zero software installation and runs directly in your browser. Unlike Veed or FreeConvert, VideoReduce is 100% free, imposes no file size limits, adds no watermarks, and never uploads your private videos to cloud servers.",
      },
      {
        question: "How to reduce video resolution or storage size?",
        answer:
          "In the compressor settings, select a lower resolution preset like 1080p, 720p, or 480p. Downscaling from 4K to 1080p immediately cuts raw video data by 75% while maintaining exceptional clarity on phone and computer screens.",
      },
    ],
  },

  // 2. Video to GIF Converter
  {
    id: "video-to-gif",
    slug: "video-to-gif",
    name: "Video to GIF Converter",
    shortName: "Make GIF",
    tagline: "Turn video clips into ultra-smooth, high-definition animated GIFs online for free",
    description:
      "Convert MP4, MOV, or WebM video clips into high quality animated GIFs using advanced two-pass palette generation. Free video to gif converter for iPhone, PC, YouTube & Twitter clips with no watermarks or server uploads.",
    category: "Conversion",
    iconName: "Film",
    badge: "High Quality",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".webm", ".mkv", ".avi"],
    outputExtension: "gif",
    outputMimeType: "image/gif",
    estimatedSpeed: "Fast (Two-Pass Palette)",
    seoTitle: "Free Video to GIF Converter Online - High Quality HD GIF Maker",
    seoDescription:
      "Convert video to GIF online free in high quality. Fast video to GIF maker for iPhone, PC, YouTube and Twitter clips with custom FPS and two-pass color palette. Best free alternative to Ezgif & Adobe Express.",
    seoKeywords: [
      "video to gif",
      "video to gif converter",
      "convert video to gif",
      "youtube video to gif",
      "ezgif video to gif",
      "twitter video to gif",
      "video to gif maker",
      "turn video to gif",
      "how to convert video to gif",
      "adobe express video to gif",
      "adobe video to gif",
      "video to gif high quality",
      "video to gif converter free",
      "video to gif iphone",
      "video to gif online",
      "iphone video to gif",
      "free video to gif converter",
      "video to gif free",
      "change video to gif",
      "video to gif adobe",
    ],
    features: [
      {
        title: "Two-Pass Color Palette",
        description: "Generates a custom 256-color palette to eliminate color banding for crystal clear, high quality GIFs.",
        icon: "Palette",
      },
      {
        title: "Custom Frame Rate & Dimensions",
        description: "Choose 10, 15, 24, or 30 FPS and custom width for ultra-smooth motion or lightweight files.",
        icon: "Gauge",
      },
      {
        title: "100% Free & Private (No Uploads)",
        description: "Turn video to GIF directly on your device with WebAssembly. No file size limits or cloud privacy risks.",
        icon: "ShieldCheck",
      },
      {
        title: "Works on iPhone, Android & PC",
        description: "Easily convert iPhone MOV clips or recorded video into animated GIFs in any modern mobile or desktop browser.",
        icon: "Smartphone",
      },
    ],
    steps: [
      {
        step: 1,
        title: "Upload Video Clip",
        description: "Select your MP4, MOV, or WebM video file (from your iPhone, Android, or PC).",
      },
      {
        step: 2,
        title: "Set Frame Rate & Dimensions",
        description: "Customize FPS (10-30 FPS) and width for the ideal balance of smoothness and file size.",
      },
      {
        step: 3,
        title: "Generate & Download GIF",
        description: "Click 'Start Converting' and instantly download your high quality animated GIF.",
      },
    ],
    faqs: [
      {
        question: "How to convert video to GIF in high quality?",
        answer:
          "To get a high quality GIF without grainy artifacts, VideoReduce.com utilizes an automated two-pass color palette generation algorithm (palettegen and paletteuse with Lanczos scaling) to capture all 256 optimal colors for your specific video footage.",
      },
      {
        question: "How do I turn an iPhone video into a GIF?",
        answer:
          "Simply upload your iPhone QuickTime MOV or MP4 video to VideoReduce.com's Video to GIF converter. It processes locally on your iOS browser (Safari/Chrome) without uploading to any server, outputting an animated GIF ready to share via iMessage, WhatsApp, or Twitter.",
      },
      {
        question: "How does this compare to Ezgif, Adobe Express, or other online GIF makers?",
        answer:
          "Unlike cloud converters like Ezgif or Adobe Express that require uploading private videos to remote servers with strict file caps, VideoReduce.com runs 100% client-side via WebAssembly. It is completely free, instant, requires no registration, and has zero server upload queues.",
      },
      {
        question: "Can I convert YouTube and Twitter video clips into GIFs?",
        answer:
          "Yes! Download or record your favorite YouTube or Twitter video clip and drop the MP4 or WebM file into our Video to GIF maker to turn it into an animated GIF in seconds.",
      },
      {
        question: "Is this video to GIF converter completely free?",
        answer:
          "Yes, 100% free with no watermarks, no sign-ups, and unlimited conversions.",
      },
    ],
  },

  // 3. Audio Extractor
  {
    id: "audio-extractor",
    slug: "audio-extractor",
    name: "Audio Extractor & Converter",
    shortName: "Extract Audio",
    tagline: "Extract pristine audio from any video into MP3, WAV, or AAC",
    description: "Rip soundtrack, speech, and sound effects from any video format into high-bitrate MP3, lossless WAV, or AAC audio files.",
    category: "Audio",
    iconName: "Music",
    badge: "Studio Audio",
    acceptedTypes: ["video/*", "audio/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".flv", ".mp3", ".wav", ".aac"],
    outputExtension: "mp3",
    outputMimeType: "audio/mpeg",
    estimatedSpeed: "Instant",
    seoTitle: "Extract Audio from Video Online Free - MP3, WAV, AAC Converter",
    seoDescription: "Extract audio tracks from MP4, MKV, MOV videos into 320kbps MP3, AAC or lossless WAV files.",
    seoKeywords: ["extract audio from video", "mp4 to mp3 converter", "video to wav", "rip audio from video"],
    features: [
      { title: "Multiple Formats", description: "Export as universal MP3, Apple AAC, or studio lossless WAV.", icon: "FileAudio" },
      { title: "High Bitrate (320kbps)", description: "Crystal-clear high fidelity encoding presets.", icon: "Radio" },
      { title: "Lightning Fast", description: "Demux and extract audio in seconds.", icon: "Zap" },
    ],
    steps: [
      { step: 1, title: "Select Video", description: "Upload any video or audio file." },
      { step: 2, title: "Choose Format", description: "Pick MP3, WAV, or AAC and select bitrate." },
      { step: 3, title: "Extract & Download", description: "Download your clean audio file." },
    ],
    faqs: [{ question: "Is WAV format lossless?", answer: "Yes, WAV exports 16-bit uncompressed PCM studio master audio." }],
  },

  // 4. Video Trimmer & Splitter
  {
    id: "video-trimmer",
    slug: "video-trimmer",
    name: "Video Trimmer & Splitter",
    shortName: "Trim Video",
    tagline: "Cut and trim videos with millisecond timeline precision",
    description: "Cut unwanted sections, trim video start and end times with live synchronized preview and ultra-fast lossless stream-copy.",
    category: "Video",
    iconName: "Scissors",
    badge: "Dual Timeline",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Instant (Lossless Copy)",
    seoTitle: "Free Video Trimmer Online - Cut & Split Video Clips Fast",
    seoDescription: "Trim and cut video clips with dual-handle timeline slider, real-time video scrub, and fast stream-copy cut.",
    seoKeywords: ["video trimmer", "cut video online", "split video", "trim mp4 online"],
    features: [
      { title: "Dual Timeline Handles", description: "Interactive start and end handles for exact cuts.", icon: "SlidersHorizontal" },
      { title: "Live Video Scrub", description: "Player follows handle movement frame by frame.", icon: "Eye" },
      { title: "Lossless Stream-Copy", description: "Instant export without re-encoding video.", icon: "Cpu" },
    ],
    steps: [
      { step: 1, title: "Load Video", description: "Upload the video you want to cut." },
      { step: 2, title: "Set Handles", description: "Drag start/end handles to mark keep segment." },
      { step: 3, title: "Trim Video", description: "Export the trimmed segment instantly." },
    ],
    faqs: [{ question: "How fast is stream-copy?", answer: "Stream-copy completes in under a second because it copies raw video packets." }],
  },

  // 5. Video Speed Controller
  {
    id: "speed-controller",
    slug: "speed-controller",
    name: "Video Speed Controller",
    shortName: "Change Speed",
    tagline: "Speed up or create cinematic slow-motion videos with pitch correction",
    description: "Adjust playback speed from 0.25x slow-motion up to 4.0x fast-forward with automated audio pitch preservation.",
    category: "Video",
    iconName: "FastForward",
    badge: "0.25x - 4x",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Video Speed Controller Online - Fast Forward & Slow Motion Video",
    seoDescription: "Speed up or slow down videos from 0.25x to 4x with audio pitch correction and smooth frame presentation.",
    seoKeywords: ["video speed controller", "speed up video online", "slow motion video maker"],
    features: [
      { title: "0.25x to 4x Multipliers", description: "One-click preset speed buttons.", icon: "Zap" },
      { title: "Audio Pitch Correction", description: "Maintains natural vocal pitch with FFmpeg atempo.", icon: "Volume2" },
      { title: "Smooth PTS Presentation", description: "Recalculates video timestamps for stutter-free playback.", icon: "Activity" },
    ],
    steps: [
      { step: 1, title: "Select Video", description: "Upload the clip you want to speed or slow." },
      { step: 2, title: "Select Multiplier", description: "Pick 0.5x, 2x, 4x, etc." },
      { step: 3, title: "Render & Save", description: "Download your speed-adjusted video." },
    ],
    faqs: [{ question: "Does pitch stay normal?", answer: "Yes, voices sound normal without chipmunk effect." }],
  },

  // 6. Video Mute
  {
    id: "video-mute",
    slug: "video-mute",
    name: "Video Mute & Audio Stripper",
    shortName: "Mute Video",
    tagline: "Remove audio tracks from any video in milliseconds",
    description: "Strip background noise, unwanted audio, or confidential speech from your videos in 1-click with zero quality loss.",
    category: "Audio",
    iconName: "VolumeX",
    badge: "1-Click",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".flv"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Instant (100ms)",
    seoTitle: "Remove Audio from Video Online Free - 1-Click Video Muter",
    seoDescription: "Mute and strip audio from MP4, MOV, WebM videos instantly without re-encoding video.",
    seoKeywords: ["mute video online", "remove audio from video", "strip audio from mp4"],
    features: [
      { title: "Zero Re-encoding", description: "Copies video stream 1:1 with pure zero loss.", icon: "Shield" },
      { title: "Sub-Second Processing", description: "Mutes even 1GB files in milliseconds.", icon: "Clock" },
      { title: "Smaller File Size", description: "Removes unnecessary audio stream channels.", icon: "ArrowDownCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select any video containing audio." },
      { step: 2, title: "Click Mute", description: "Click 1-Click Mute to strip audio." },
      { step: 3, title: "Download Silent Video", description: "Save your clean video immediately." },
    ],
    faqs: [{ question: "Does video quality change?", answer: "Not a single pixel changes; video is stream-copied bit for bit." }],
  },

  // 7. Universal Format Converter
  {
    id: "format-converter",
    slug: "format-converter",
    name: "Universal Video Format Converter",
    shortName: "Convert Format",
    tagline: "Transcode seamlessly between MP4, WebM, MKV, MOV, AVI, and FLV",
    description: "Convert video containers and codecs across all major formats for maximum device compatibility and web streaming.",
    category: "Conversion",
    iconName: "RefreshCw",
    badge: "All Formats",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".flv", ".wmv", ".m4v"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Universal Video Converter Online - Convert MP4, WebM, MKV, MOV, AVI",
    seoDescription: "Convert videos between MP4, WebM, MKV, MOV, AVI, and FLV right inside your web browser.",
    seoKeywords: ["video format converter", "convert mov to mp4", "convert mkv to mp4", "webm to mp4 converter"],
    features: [
      { title: "6+ Major Formats", description: "Support for MP4, WebM, MKV, MOV, AVI, and FLV.", icon: "FileCode" },
      { title: "Web Streaming Optimized", description: "Applies faststart flags for progressive web playback.", icon: "Globe" },
      { title: "High Fidelity", description: "Crisp H.264 / VP8 transcode with custom presets.", icon: "Sparkles" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select any video file." },
      { step: 2, title: "Select Target Format", description: "Pick MP4, WebM, MKV, or MOV." },
      { step: 3, title: "Convert & Save", description: "Download your newly formatted video." },
    ],
    faqs: [{ question: "Which format is best for social media?", answer: "MP4 with H.264 and AAC is 100% universal across all platforms." }],
  },

  // 8. Social Aspect Ratio Resizer
  {
    id: "aspect-ratio-resizer",
    slug: "aspect-ratio-resizer",
    name: "Social Aspect Ratio Resizer",
    shortName: "Resize for Social",
    tagline: "Format videos for TikTok, Reels, Shorts (9:16), Instagram (1:1), and YouTube (16:9)",
    description: "Fit videos perfectly to 9:16 vertical, 1:1 square, or 16:9 widescreen formats using smart center cropping or letterbox padding.",
    category: "Optimization",
    iconName: "Smartphone",
    badge: "TikTok & Reels",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Social Media Video Resizer - Fit for TikTok, Reels, YouTube Shorts",
    seoDescription: "Resize landscape videos to 9:16 vertical for TikTok and Instagram Reels with crop or letterbox padding.",
    seoKeywords: ["video aspect ratio resizer", "resize video for tiktok", "convert horizontal to vertical video"],
    features: [
      { title: "Social Presets", description: "9:16 Reels/Shorts, 1:1 Instagram, 16:9 YouTube.", icon: "LayoutGrid" },
      { title: "Crop vs Pad", description: "Choose full screen center-crop or elegant letterbox padding.", icon: "Maximize2" },
      { title: "Crisp 1080p Dimensions", description: "Standard high definition exports.", icon: "CheckCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select your landscape or square video." },
      { step: 2, title: "Pick Aspect Ratio", description: "Choose 9:16, 1:1, 16:9 and Crop/Pad mode." },
      { step: 3, title: "Export & Post", description: "Download ready-to-publish social video." },
    ],
    faqs: [{ question: "What is letterbox padding?", answer: "Padding keeps the full video in view and fills empty borders with clean black margins." }],
  },

  // 9. Video Watermark & Logo Adder
  {
    id: "video-watermark",
    slug: "video-watermark",
    name: "Video Watermark & Logo Adder",
    shortName: "Add Watermark",
    tagline: "Add custom text watermark or transparent PNG logo branding to your videos",
    description: "Protect and brand your video clips with customizable text watermarks or image logos with 5 position presets and opacity control.",
    category: "Video",
    iconName: "Image",
    badge: "Branding",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Add Watermark & Logo to Video Online Free (No Server Upload)",
    seoDescription: "Add text watermarks or PNG logos to videos in browser. Custom opacity, position controls, 100% private.",
    seoKeywords: ["add watermark to video", "video logo adder", "watermark video online free", "brand video watermark"],
    features: [
      { title: "Text & Image Watermarks", description: "Type custom text or upload transparent PNG logo.", icon: "Image" },
      { title: "5 Position Presets", description: "Place in Top-Left, Top-Right, Bottom-Left, Bottom-Right, or Center.", icon: "LayoutGrid" },
      { title: "Opacity & Size Slider", description: "Subtle translucent branding with scale controls.", icon: "Sliders" },
    ],
    steps: [
      { step: 1, title: "Select Video", description: "Upload the video you want to brand." },
      { step: 2, title: "Configure Watermark", description: "Type text or select position & opacity." },
      { step: 3, title: "Apply & Download", description: "Export your newly branded video." },
    ],
    faqs: [{ question: "Can I use transparent PNG logos?", answer: "Yes, alpha transparency is fully preserved." }],
  },

  // 10. Video Rotate & Flip
  {
    id: "video-rotate",
    slug: "video-rotate",
    name: "Video Rotate & Flip",
    shortName: "Rotate Video",
    tagline: "Rotate sideways videos by 90°, 180°, 270° or flip horizontally/vertically",
    description: "Fix sideways smartphone recordings and mirror videos horizontally or vertically with 1-click rotation presets.",
    category: "Video",
    iconName: "RotateCw",
    badge: "Orientation",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Rotate Video Online - 90, 180, 270 Degree & Flip Mirror",
    seoDescription: "Rotate smartphone videos 90, 180, 270 degrees clockwise or flip horizontal/vertical mirror free in browser.",
    seoKeywords: ["rotate video online", "fix sideways video", "rotate mp4 90 degrees", "flip video horizontally"],
    features: [
      { title: "90°, 180°, 270° Rotation", description: "Fix any landscape or portrait phone angle.", icon: "RotateCw" },
      { title: "Horizontal & Vertical Flip", description: "Mirror video selfie recordings easily.", icon: "RefreshCw" },
      { title: "Maintains Full Quality", description: "Crisp re-encode with proper metadata orientation.", icon: "CheckCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select your sideways or inverted video." },
      { step: 2, title: "Choose Rotation Angle", description: "Click 90° Clockwise, 180°, 270° or Flip." },
      { step: 3, title: "Save Video", description: "Download your upright video." },
    ],
    faqs: [{ question: "Why are some phone videos sideways?", answer: "Some cameras save incorrect rotation metadata; this tool hardcodes the orientation." }],
  },

  // 11. Video Reverse / Rewind Maker
  {
    id: "video-reverse",
    slug: "video-reverse",
    name: "Video Reverse & Rewind Maker",
    shortName: "Reverse Video",
    tagline: "Reverse any video online free — play video backwards with audio for rewind effects",
    description:
      "Free online video reverse tool to play any video backwards. Create viral rewind effects for TikTok, YouTube Shorts, and Instagram Reels. Works with any size video — no file limits, 100% private in your browser.",
    category: "Video",
    iconName: "Rewind",
    badge: "Rewind FX",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast (Wasm)",
    seoTitle: "Free Video Reverse Online — Play Video Backwards & Rewind Maker",
    seoDescription:
      "Reverse video online for free. Play any video backwards with reversed or muted audio. Create viral rewind effects, loop videos in reverse, and edit reversed clips — no app install needed.",
    seoKeywords: [
      "video reverse",
      "video reverse online",
      "video reverse search",
      "video reverse search engine",
      "how to make a video reverse",
      "video reverse app",
      "video reverse image search",
      "google video reverse search",
      "how to make video reverse",
      "search by video reverse",
      "video reverse lookup",
      "search video reverse",
      "loop video reverse",
      "video reverse tool",
      "edit video reverse",
      "video reverse editor",
      "video reverse prompt generator",
      "how to play video reverse",
    ],
    features: [
      {
        title: "Reverse Any Size Video",
        description: "Unlike other tools limited to 8MB or 10MB, VideoReduce reverses videos of any file size — 100MB, 1GB, or even 4K footage — directly in your browser.",
        icon: "Rewind",
      },
      {
        title: "Reverse Audio or Mute",
        description: "Choose to reverse the audio soundtrack for a true rewind effect, or mute audio entirely for clean silent reverse clips.",
        icon: "Volume2",
      },
      {
        title: "Loop Video in Reverse",
        description: "Create seamless forward-then-reverse loop effects for mesmerizing boomerang-style social media content.",
        icon: "RefreshCw",
      },
      {
        title: "100% Free & Private",
        description: "No app install, no file upload to servers. Edit and reverse videos entirely inside your browser RAM via WebAssembly.",
        icon: "ShieldCheck",
      },
    ],
    steps: [
      {
        step: 1,
        title: "Upload Any Video",
        description: "Select any MP4, MOV, MKV, or WebM video file of any size from your device.",
      },
      {
        step: 2,
        title: "Choose Reverse Options",
        description: "Select reverse audio, mute audio, or loop video reverse playback mode.",
      },
      {
        step: 3,
        title: "Download Reversed Video",
        description: "Click Reverse and download your backwards-playing video in seconds.",
      },
    ],
    faqs: [
      {
        question: "How to make a video reverse online for free?",
        answer:
          "Upload your video to VideoReduce.com's Video Reverse tool, select whether to reverse audio or mute it, and click Reverse. The WebAssembly engine processes the video entirely in your browser — no server upload, no file size limits, completely free.",
      },
      {
        question: "Can I reverse any size video, not just 8MB or 10MB?",
        answer:
          "Yes! Unlike Discord compressors or other tools that cap files at 8MB or 10MB, VideoReduce.com processes videos of any size — even 1GB+ 4K footage — directly in your browser's memory with zero file restrictions.",
      },
      {
        question: "How to play a video in reverse with audio?",
        answer:
          "Select 'Reverse Audio' mode in VideoReduce's reverse tool. The engine will reverse both the video frames and the audio track, creating a genuine rewind effect where speech and music play backwards.",
      },
      {
        question: "Can I loop a video in reverse (boomerang effect)?",
        answer:
          "Yes! Use the loop reverse option to create a forward-then-backward seamless loop. This is perfect for boomerang-style effects on Instagram, TikTok, and YouTube Shorts.",
      },
      {
        question: "Is this video reverse tool better than a phone app?",
        answer:
          "VideoReduce.com works instantly in any browser (Safari, Chrome, Edge) without installing apps, creating accounts, or dealing with ads and watermarks. It also handles much larger files than most mobile reverse video apps.",
      },
    ],
  },

  // 12. Video Frame Extractor
  {
    id: "frame-extractor",
    slug: "frame-extractor",
    name: "Video Frame Extractor & Screenshot Grabber",
    shortName: "Grab Frame",
    tagline: "Capture high-resolution PNG or JPG screenshots from exact video timestamps",
    description: "Extract pristine, uncompressed full-resolution still photo frames and thumbnails from any video clip at exact millisecond marks.",
    category: "Conversion",
    iconName: "Eye",
    badge: "HD Snapshot",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi"],
    outputExtension: "png",
    outputMimeType: "image/png",
    estimatedSpeed: "Instant",
    seoTitle: "Extract Frame from Video Online - High Res Video Screenshot Grabber",
    seoDescription: "Capture exact HD & 4K frames from video clips as PNG or JPG images with live timeline scrubber.",
    seoKeywords: ["extract frame from video", "video screenshot grabber", "video to photo converter", "capture frame from mp4"],
    features: [
      { title: "Millisecond Precision", description: "Scrub to the exact frame you want to extract.", icon: "SlidersHorizontal" },
      { title: "Lossless PNG Export", description: "Saves maximum native video resolution without compression artifacts.", icon: "Image" },
      { title: "Instant Snapshot", description: "Demuxes frame in under 200 milliseconds.", icon: "Zap" },
    ],
    steps: [
      { step: 1, title: "Select Video", description: "Upload your video file." },
      { step: 2, title: "Scrub to Frame", description: "Use timeline slider to find the perfect shot." },
      { step: 3, title: "Save Photo", description: "Download high-res PNG or JPG image." },
    ],
    faqs: [{ question: "Is the snapshot full resolution?", answer: "Yes! If the video is 1080p or 4K, the image is exported at the full native pixel dimensions." }],
  },

  // 13. Video Filters & Color Grading
  {
    id: "video-filters",
    slug: "video-filters",
    name: "Video Filters & Color Grading",
    shortName: "Color Filters",
    tagline: "Apply cinematic color grading, vintage filters, and brightness adjustments",
    description: "Enhance your footage with aesthetic presets (Cyberpunk, Vintage Sepia, B&W, Warm Sunset) or adjust brightness, contrast, and saturation.",
    category: "Video",
    iconName: "Sun",
    badge: "Cinematic",
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Video Color Filters & Grading Online - Free Video Effects",
    seoDescription: "Apply vintage, cyberpunk, black and white filters or adjust brightness, contrast, and saturation in browser.",
    seoKeywords: ["video color grading online", "video filters free", "adjust video brightness", "black and white video filter"],
    features: [
      { title: "Cinematic Color Presets", description: "Cyberpunk, Sepia, Vintage Film, B&W, Warm Sunset.", icon: "Palette" },
      { title: "Fine Slider Controls", description: "Fine-tune Brightness, Contrast, Saturation, and Gamma.", icon: "Sliders" },
      { title: "Instant Playback", description: "Download studio-color graded video.", icon: "PlayCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select the video you want to enhance." },
      { step: 2, title: "Choose Filter or Sliders", description: "Pick a preset or adjust color sliders." },
      { step: 3, title: "Render & Download", description: "Export your enhanced video." },
    ],
    faqs: [{ question: "Can I adjust dark videos?", answer: "Yes, increasing Brightness and Gamma will brighten underexposed dark video clips." }],
  },

  // 14. GIF to MP4 Video Converter
  {
    id: "gif-to-video",
    slug: "gif-to-video",
    name: "GIF to MP4 Video Converter",
    shortName: "GIF to MP4",
    tagline: "Convert heavy animated GIFs into 95% smaller looping MP4 videos online free",
    description:
      "Convert animated GIF to MP4 video online for free. Transform heavy .gif files from Twitter, Photoshop, Mac, or PC into ultra-lightweight, looping H.264 MP4 videos directly in your browser with zero server uploads.",
    category: "Conversion",
    iconName: "Film",
    badge: "95% Smaller",
    acceptedTypes: ["image/gif"],
    acceptedExtensions: [".gif"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast (Wasm SIMD)",
    seoTitle: "Free GIF to MP4 Converter Online - Convert Animated GIF to Video (Loop)",
    seoDescription:
      "Convert GIF to MP4 online free in high quality. Fast animated .gif to MP4 converter with seamless looping and 95% file size reduction for Twitter, Mac, Photoshop, and PC. Best free alternative to Ezgif.",
    seoKeywords: [
      "gif to mp4",
      "convert gif to mp4",
      "gif to mp4 converter",
      "ezgif gif to mp4",
      "how to convert gif to mp4",
      "twitter gif to mp4",
      "gif to mp4 converter free",
      "convert gif to mp4 free",
      ".gif to mp4",
      "convert gif to mp4 photoshop",
      "how to convert a gif to mp4",
      "convert animated gif to mp4",
      "gif to mp4 loop",
      "change gif to mp4",
      "converting gif to mp4",
      "convert gif to mp4 online free",
      "turn gif to mp4",
      "gif to mp4 online",
      "convert gif to mp4 mac",
      "animated gif to mp4",
    ],
    features: [
      {
        title: "95% File Size Reduction",
        description: "Shrink a bulky 30MB animated GIF into an ultra-lightweight 1.5MB MP4 video with identical visual smoothness.",
        icon: "Minimize2",
      },
      {
        title: "Seamless Looping MP4 Playback",
        description: "Encodes with standard YUV420p and HTML5 video looping flags for instant, stutter-free autoplay.",
        icon: "RefreshCw",
      },
      {
        title: "100% Free & Private (No Uploads)",
        description: "Convert .gif to MP4 directly inside your browser memory via WebAssembly without cloud queues or privacy risks.",
        icon: "ShieldCheck",
      },
      {
        title: "Universal Mac, PC & Mobile Support",
        description: "Easily turn Photoshop, Twitter, or Discord GIFs into universally compatible MP4 videos on Mac, Windows, iOS, and Android.",
        icon: "CheckCircle",
      },
    ],
    steps: [
      {
        step: 1,
        title: "Upload Animated GIF",
        description: "Select any .gif file from your computer, Mac, or phone.",
      },
      {
        step: 2,
        title: "Choose Compression Preset",
        description: "Pick High Quality (CRF 20) or Maximum Compression (CRF 26) with standard H.264 encoding.",
      },
      {
        step: 3,
        title: "Convert to MP4 & Download",
        description: "Click 'Convert to MP4' and download your ultra-lean looping video in seconds.",
      },
    ],
    faqs: [
      {
        question: "How to convert animated GIF to MP4 online for free?",
        answer:
          "Simply drag and drop your .gif file into VideoReduce.com's GIF to MP4 converter and click Convert. The WebAssembly engine decodes each GIF frame and encodes it into standard H.264 MP4 right in your browser.",
      },
      {
        question: "Why is MP4 so much smaller than animated GIF?",
        answer:
          "GIF is an outdated 1987 format that stores every frame as a full uncompressed image. MP4 uses advanced inter-frame video compression (H.264), storing only the differences between frames. This results in up to 95% smaller file sizes with better frame rates.",
      },
      {
        question: "How do I convert Twitter GIFs to MP4?",
        answer:
          "Twitter actually serves its GIFs as video streams. If you have saved a Twitter .gif file, drop it into VideoReduce.com to convert and clean it into a standalone MP4 video that can be shared or embedded anywhere.",
      },
      {
        question: "Can I convert GIF to MP4 on Mac without Photoshop?",
        answer:
          "Yes! Instead of using heavy desktop software like Adobe Photoshop, VideoReduce.com runs entirely in your Mac browser (Safari, Chrome, Firefox) without needing any software installations or subscriptions.",
      },
      {
        question: "How does VideoReduce compare to Ezgif GIF to MP4?",
        answer:
          "Ezgif uploads your file to their remote web server with upload queues and file size restrictions. VideoReduce processes your GIF locally in your browser memory via WebAssembly — offering faster processing, zero file caps, and complete data privacy.",
      },
    ],
  },

  // 15. Volume Booster & Normalizer
  {
    id: "volume-booster",
    slug: "volume-booster",
    name: "Volume Booster & Audio Normalizer",
    shortName: "Boost Volume",
    tagline: "Boost low video audio up to 300% or apply broadcast audio normalization",
    description: "Amplify quiet voices and sound in videos up to 3x, or apply standard EBU R128 audio normalization to fix uneven volume levels.",
    category: "Audio",
    iconName: "Volume2",
    badge: "Up to 300%",
    acceptedTypes: ["video/*", "audio/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".mp3", ".wav"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Instant",
    seoTitle: "Video Volume Booster Online - Amplify Quiet Audio & Normalize Sound",
    seoDescription: "Increase video and audio volume up to 300% or apply broadcast normalization for free in browser.",
    seoKeywords: ["video volume booster", "increase video volume", "audio normalizer online", "boost mp4 volume"],
    features: [
      { title: "Up to 300% Amplification", description: "Boost quiet microphone recordings with clean gain.", icon: "Volume2" },
      { title: "EBU R128 Normalizer", description: "Broadcast standard loudnorm leveling prevents ear-piercing jumps.", icon: "Radio" },
      { title: "Zero Video Re-encoding", description: "Transcodes audio track with video stream-copy for maximum speed.", icon: "Zap" },
    ],
    steps: [
      { step: 1, title: "Upload Video / Audio", description: "Select file with quiet or uneven audio." },
      { step: 2, title: "Set Volume Boost", description: "Choose 150%, 200%, 300% or Normalize." },
      { step: 3, title: "Download Loud Media", description: "Save your amplified video file." },
    ],
    faqs: [{ question: "What is Audio Normalization?", answer: "Normalization automatically boosts quiet parts and reins in loud peaks so everything sounds balanced." }],
  },

  // 16. Audio Noise Reduction / De-Noiser
  {
    id: "audio-denoiser",
    slug: "audio-denoiser",
    name: "Audio Noise Reduction & De-Noiser",
    shortName: "De-Noise Audio",
    tagline: "Remove microphone hiss, fan background noise, and room hum",
    description: "Clean up your video soundtrack and voice recordings with advanced FFT spectral noise suppression directly in your browser.",
    category: "Audio",
    iconName: "Mic",
    badge: "Clean Audio",
    acceptedTypes: ["video/*", "audio/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".mp3", ".wav"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Fast",
    seoTitle: "Remove Background Noise from Video Online Free - Audio De-Noiser",
    seoDescription: "Remove mic hiss, AC fan noise, and background hum from video and audio tracks with WebAssembly.",
    seoKeywords: ["remove background noise from video", "audio denoiser online", "clean mic hiss", "noise reduction video"],
    features: [
      { title: "FFT Spectral Filter", description: "Suppresses steady state noise (fans, air conditioning, electrical hum).", icon: "Mic" },
      { title: "Noise Floor Adjustment", description: "Customizable sensitivity for light or aggressive noise reduction.", icon: "Sliders" },
      { title: "Crystal-Clear Speech", description: "Enhances vocal clarity for podcasts and webinars.", icon: "CheckCircle" },
    ],
    steps: [
      { step: 1, title: "Upload Recording", description: "Select video or audio with background noise." },
      { step: 2, title: "Adjust Noise Sensitivity", description: "Choose light, medium, or deep suppression." },
      { step: 3, title: "Download Clean Audio", description: "Save your crystal-clear recording." },
    ],
    faqs: [{ question: "What types of noise does it remove?", answer: "It excels at continuous background noise like computer fans, AC hums, and microphone hiss." }],
  },

  // 17. Metadata & EXIF Stripper
  {
    id: "metadata-stripper",
    slug: "metadata-stripper",
    name: "Metadata & EXIF Privacy Shield",
    shortName: "Strip Metadata",
    tagline: "Wipe GPS location, camera serials, author info, and timestamps in 1-click",
    description: "Ensure complete privacy before sharing videos online by scrubbing GPS coordinates, phone serials, software tags, and timestamps.",
    category: "Privacy & Pro",
    iconName: "Lock",
    badge: "Privacy Shield",
    acceptedTypes: ["video/*", "audio/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Instant (50ms)",
    seoTitle: "Remove Video Metadata & EXIF Online Free - Privacy Shield",
    seoDescription: "Strip GPS location tags, camera model info, and creator metadata from video files in 1-click.",
    seoKeywords: ["remove video metadata", "strip exif from video", "remove gps from mp4", "clean video metadata"],
    features: [
      { title: "Scrub GPS & Device Info", description: "Wipes camera model, creation time, and geolocation tags.", icon: "Lock" },
      { title: "Instant Stream Copy", description: "Cleans metadata in milliseconds without touching video quality.", icon: "Zap" },
      { title: "100% Anonymous Sharing", description: "Safely share videos on social media without privacy leaks.", icon: "ShieldCheck" },
    ],
    steps: [
      { step: 1, title: "Upload Video", description: "Select any video file." },
      { step: 2, title: "Click Strip Metadata", description: "Click 1-Click Scrub to clean all metadata." },
      { step: 3, title: "Download Anonymous File", description: "Save your privacy-protected video." },
    ],
    faqs: [{ question: "Does this affect video quality?", answer: "Zero quality loss. The video and audio streams are copied 1:1, only header tags are removed." }],
  },

  // 18. FFmpeg Developer Terminal
  {
    id: "ffmpeg-terminal",
    slug: "ffmpeg-terminal",
    name: "FFmpeg Developer Terminal",
    shortName: "Wasm Terminal",
    tagline: "Run custom FFmpeg commands directly in your browser with live log stream",
    description: "A sandbox for engineers, editors, and creators to execute raw FFmpeg command arguments with custom filters, presets, and real-time logs.",
    category: "Privacy & Pro",
    iconName: "Terminal",
    badge: "Dev Mode",
    acceptedTypes: ["video/*", "audio/*", "image/*"],
    acceptedExtensions: [".mp4", ".mov", ".mkv", ".webm", ".avi", ".gif", ".mp3", ".wav"],
    outputExtension: "mp4",
    outputMimeType: "video/mp4",
    estimatedSpeed: "Variable",
    seoTitle: "Online FFmpeg Command Runner - Browser-Based WebAssembly Terminal",
    seoDescription: "Execute custom FFmpeg CLI commands in your browser with WebAssembly. Sandbox with recipes and live log terminal.",
    seoKeywords: ["ffmpeg online", "run ffmpeg in browser", "ffmpeg wasm terminal", "ffmpeg command runner"],
    features: [
      { title: "Raw Command Line", description: "Type any valid FFmpeg flags (-vf, -af, -c:v, -crf, etc.).", icon: "Terminal" },
      { title: "Pre-Built Recipes", description: "One-click load templates for 60fps, desaturate, high bitrate, etc.", icon: "FileCode" },
      { title: "Live Real-Time Logs", description: "Full standard error stream output from FFmpeg core.", icon: "Activity" },
    ],
    steps: [
      { step: 1, title: "Upload Input File", description: "Pick any media file." },
      { step: 2, title: "Enter FFmpeg Flags", description: "Type custom args or pick a template recipe." },
      { step: 3, title: "Execute & Download", description: "Run Wasm engine and download output." },
    ],
    faqs: [{ question: "Can I use complex filtergraphs?", answer: "Yes, -vf, -af, and -filter_complex are fully supported by the Wasm engine." }],
  },
];

export function getToolBySlug(slug: string): ToolMetadata | undefined {
  return TOOLS.find((tool) => tool.slug === slug || tool.id === slug);
}
